---
- name: update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  when: baseline_upgrade_all

- name: Ensure Telnet not installed
  ansible.builtin.package:
    name: telnet
    state: absent

- name: disable ctrl-alt-del
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: true
  notify: Systemd_daemon_reload

- name: Audit vendor-supported release
  ansible.builtin.debug:
    msg: "System is running a vendor supported release as per assert checks at the beginning of the playbook - {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }}"

- name: Install baseline packages
  ansible.builtin.apt:
    name: "{{ baseline_packages }}"
    state: present

- name: Create Users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.count | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
  loop: "{{ baseline_users }}"

- name: Deploy MOTD
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'

- name: Ensure timezone is set
  community.general.timezone:
    name: America/Los_Angeles
  notify: Restart cron

- name: Ensure chrony service is enabled and running
  ansible.builtin.systemd:
    name: chrony.target
    enabled: true
    state: started

- name: SSHD PernitRootLogin no
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: sshd_restart

- name: Create opt scripts directory
  ansible.builtin.file:
    path: /opt/scripts
    state: directory
    mode: '0750'
    owner: root
    group: root

- name: Create opt scripts subdirectories
  ansible.builtin.file:
    path: "/opt/scripts/{{ item }}"
    state: directory
    owner: root
    group: root
  loop: "{{ baseline_opt_dirs }}"

- name: Set swappiness when mem greater than 4gb
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-baseline.conf
  when: ansible_facts['memtotal_mb'] | int > 4096

- name: Check motd
  ansible.builtin.stat:
    path: /etc/motd
  register: motd

- name: If motd exists
  ansible.builtin.debug:
    msg: "motd exists, it's size is {{ motd.stat.size }}"
  when: motd.stat.exists

- name: If motd not exist
  ansible.builtin.debug:
    msg: "motd does not exist"
  when: not motd.stat.exists




