---
- name: Provision build instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: group_vars/all/aws.yml
  vars:
    vpc_subnet_id: subnet-dc86a2b8
    sg_id: sg-014c8a854437e8d33

  tasks:
    - name: Find latest Ubuntu 24.04 AMI
      amazon.aws.ec2_ami_info:
        region: "{{ aws_region }}"
        owners: "099720109477"
        filters:
          name: "ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"
          state: available
      register: ami_search

    - name: Set latest Ubuntu AMI id
      ansible.builtin.set_fact:
        base_ami: "{{ (ami_search.images | sort(attribute='creation_date') | last).image_id }}"

    - name: Show AMI id
      ansible.builtin.debug:
        msg: "{{ base_ami }}"

    - name: Launch build instance
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        name: baseline_build
        image_id: "{{ base_ami }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        security_group: "{{ sg_id }}"
        network:
          assign_public_ip: true
        state: running
        wait: true
      register: build_instance

    - name: Add to in-memory inventory
      ansible.builtin.add_host:
        name: "{{ build_instance.instances[0].public_ip_address }}"
        groups: build
        ansible_user: ubuntu
        instance_id: "{{ build_instance.instances[0].instance_id }}"

    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: "{{ build_instance.instances[0].public_ip_address }}"
        port: 22
        delay: 10
        timeout: 300

- name: Apply baseline 
  hosts: build
  become: true
  roles:
    - baseline

- name: Reboot for safe measure
  hosts: build
  become: true
  tasks:
    - ansible.builtin.reboot:
        reboot_timeout: 300

- name: Prepare ec2 for AMI
  hosts: build
  become: true
  tasks:
    - name: Clean apt cache
      ansible.builtin.apt:
        clean: true
        autoremove: true
    - name: Find apt lists
      ansible.builtin.find:
        paths: /var/lib/apt/lists/
        recurse: true
      register: apt_lists
    - name: Clean apt lists directory
      ansible.builtin.file:
        state: absent
        path: "{{ item.path }}"
      loop: "{{ apt_lists.files }}"
      loop_control:
        label: "{{ item.path }}"
    - name: Clean bash history
      ansible.builtin.file:
        path: /home/ec2-user/.bash_history
        state: absent
    - name: Find authorized keys
      ansible.builtin.find:
        paths: /home
        patterns: authorized_keys
        recurse: true
      register: user_keys
    - name: Delete authorized keys
      ansible.builtin.file:
        state: absent
        path: "{{ item.path }}"
      loop: "{{ user_keys.files }}"
    - name: Find SSH host keys
      ansible.builtin.find:
        paths: /etc/ssh/
        patterns: "ssh_host_*"
      register: ssh_host
    - name: Delete SSH host keys
      ansible.builtin.file:
        state: absent
        path: "{{ item.path }}"
      loop: "{{ ssh_host.files }}"
      loop_control:
        label: "{{ item.path }}"
    - name: Cloud init clean
      ansible.builtin.shell: clout-init clean --logs

- name: Bake and clean
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files: group_vars/all/aws.yml
  tasks:
    - name: Create AMI
      amazon.aws.ec2_ami:
        region: "{{ aws_region}}"
        instance_id: "{{ hostvars[groups['build'][0]]['instance_id'] }}"
        name: "ubuntu-24.04-baseline-{{ ansible_date_time.iso8601_basic_short | default(lookup('pipe','date +%Y%m%d%H%M')) }}"
        wait: true
        tags:
          Baseline: "True"
          BuiltBy: "ansible - pstu"
          SourceAMI: "{{ base_ami }}"
      register: new_ami

    - name: Terminate build instance
      amazon.aws.ec2_instance:
        region: "{{ aws_region }}"
        instance_ids: "{{ hostvars[groups['build'][0]]['instance_id'] }}"
        state: absent
        wait: true
